#!/bin/bash
sudo su
sed -i 's/.*PasswordAuthentication no/Passwordauthentication yes/g' /etc/ssh/sshd_config
sed -i 's/.*#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
service sshd restart
amazon-linux-extras install epel
amazon-linux-extras install ansible2